#!/bin/sh

# It is highly recommended to put this to your git pre-commit hook, to format your code
# before checking anything in.

pylint --rcfile $ASSASSYN_HOME/python/.pylintrc $ASSASSYN_HOME/python/assassyn
pytest -n 8 $ASSASSYN_HOME/python/ci-tests
