#!/bin/sh

set -euxo pipefail
# It is highly recommended to put this to your git pre-commit hook, to format your code
# before checking anything in.

cargo check --all-targets
cargo fmt --all
cargo clippy -- -Dclippy::all

ASSASSYN_REPO=`git rev-parse --show-toplevel`

pylint --rcfile $ASSASSYN_REPO/python/.pylintrc $ASSASSYN_REPO/python/assassyn
